language: shell
os: windows
python:
- '3.8'
- '3.7'
before_install:
- choco install python --version 3.8.5
- cp /c/Python38/python.exe /c/Python38/python3.8.exe
- python3.8 -m pip install --upgrade pip
- choco install python --version 3.7.9 --side-by-side
- cp /c/Python37/python.exe /c/Python37/python3.7.exe
- python3.7 -m pip install --upgrade pip
env:
  global:
  - PATH=/c/Python38:/c/Python38/Scripts:/c/Python37:/c/Python37/Scripts:$PATH
  - TWINE_USERNAME=__token__
  - secure: QMUVS2O52xI1mjjtTDgdqMji1uCH9GdQbiWB0Zw/kDW7acAOqIYRCEXhL9q1Hrl7J6snJMP1GlrSsUg+aqUvmbT0jzOV7rwIQbrAx8Py0C7PFeLe19rmddLRA0GfsiaUmFmkQwJLfLedj/nZV6DQlLFBtcHlaKnQqk6OPeFlfh9Aqt0J1Q41rW+auVXgxevi4ZE2+mWF2LUqUcZ7kilVO82XAel1ZQkTtzFdeJMrQrnH+LG1V7xdvtH/qeiKSpOX40fppptbzD6O6xg1cbyfDMeguOVGLQazqTFSkmew/Z0waoO7UQa3+ozVpNiwzaRf10LhwhwQNrHBtJJWOey4TczL29Xxhru3IiuSnplos3JqY+ZYN4OBygkebWo8p6rRAAvVU608vdXGAaRJLmNAUSMCRg7C4jISoIDjo9vwq3KJFNDIDJ0AKqE9kfEvGL1urHOXuP4cMXutQSdROr328d3cZaj/PXvwmiiXWN/Q72M1l3A7Y58UVSInU2CllZQMN0sWF04aFngJSMhP72qUt8H/zn5ts6odSdfGGXc1SKIiSe0/zSlfualEgxuhZBLeO1B+rSosYbNDSVpbawDp837laOH2RtNMdfrFLPqOd4Q/7z2yfFddcAkO9kBdeXMZhq4D3zzng5B36vX/FDneBOuv/zsA32OwaLQHwXzIsio=
  - secure: bLtDJtQBxmLzuneFEJtM4L39g13Y/pLNzLSqbASRx3VYUFh/auyXNSE8Fa8jGrmuXA++YYTXGF8viJDlinkxka3Jc7PmijOCEtKdq5ZgaIQDK94sqyDt8vq/NDfvKteeyfUN4gFNzOXYaqaXjMtaKmD8995R6qDnCf+0BgRlfMyYdlEj/5VfYQV8m95a5ahlM8fioIA8KB1J93CpQjnPrze3He9lZgVXJloKdlejU49hGSOM8N+XgMuOrB3lI5CPPeU6XYJ+PqDxOxhSUqZlZxZCUUjAbJ/ietMQpZ2X/XqT0WD9P0tLWYRpno08kNgEOw91cggjg0CPhv1ji0K6YEBDdZRaZSbWEPOODIL9NgO8lnMrxxEC98ApZyHA5rg4wWtPGQuY5oQ9AltC2FL4yvwT38xFhUPFoThdFc+Bamsyawv09MrQtztkk8KcZTODAPV29OWjM9Lq+xOJbm/cKtrrz17V/t1NkUyCefhfU+235681X4BXmGMDdBi7mKkW6i3pMPhh30/oz1rGU2pGPepCyAguqd7CMq+G0QOH9Zy42HujPpKZEHanCTcdFdemIjHv5lVwumNkBBAJwLnFnYNHeMG+dGh3wKoLlhv6bCWujWeG2SkJxkAzGP48hjhaE0AFMTe71ViJevKSMyhIhu62jrkBsdDCGoYF1tjUfl4=
install:
- pip --version
- pip install --upgrade tox-travis
script:
- tox --showconfig
- tox --travis-after --verbose
after_success:
- ls -alt
- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: script
  edge: true
  cleanup: false
  script: bash .travis/deploy.sh
  on:
    tags: true
    repo: elbakramer/koapy
