[tool.poetry]
name = "koapy"
version = "0.3.5"
description = "Kiwoom Open Api Python"
license = "MIT OR Apache-2.0 OR GPL-3.0-or-later"
authors = ["Yunseong Hwang <kika1492@gmail.com>"]
maintainers = ["Yunseong Hwang <kika1492@gmail.com>"]
readme = "README.rst"
homepage = "https://github.com/elbakramer/koapy"
repository = "https://github.com/elbakramer/koapy"
documentation = "https://koapy.readthedocs.io/en/latest/"
keywords = ["kiwoom", "kiwoom-open-api"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: English",
    "Natural Language :: Korean",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Environment :: Console",
    "Environment :: X11 Applications :: Qt",
    "Topic :: Office/Business :: Financial",
]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"

click = "^7.1.2"
"discord.py" = "^1.7.1"
exchange-calendars = "^3.0.2"
grpcio = "^1.37.0"
grpcio-tools = "^1.37.0"
korean-lunar-calendar = "^0.2.1"
numpy = "^1.20.2"
openpyxl = "^3.0.7"
pandas = "^1.2.4"
protobuf = "^3.15.8"
pyhocon = "^0.3.57"
PySide2 = "^5.15.2"
pytz = "^2021.1"
QtPy = "^1.9.0"
requests = "^2.25.1"
Rx = "^3.2.0"
schedule = "^1.1.0"
Send2Trash = "^1.5.0"
SQLAlchemy = "^1.4.11"
tabulate = "^0.8.9"
tqdm = "^4.60.0"
tzlocal = "^2.1"
wrapt = "^1.12.1"

pywin32 = { version = "^300", markers = "sys_platform == 'win32'" }
pywinauto = { version = "^0.6.8", markers = "sys_platform == 'win32'" }

backtrader = { version = "^1.9.76.123", optional = true }
matplotlib = { version = "^3.4.1", optional = true }

PyQt5 = { version = "^5.15.4", optional = true }

[tool.poetry.dev-dependencies]
astroid = "^2.5.6"
black = "^21.4b2"
bump2version = "^1.0.1"
click = "^7.1.2"
codecov = "^2.1.11"
coverage = "^5.5"
flake8 = "^3.9.1"
isort = "^5.8.0"
pip = "^21.1"
poetry = "^1.1.6"
pre-commit = "^2.12.1"
Pygments = "^2.8.1"
pylint = "^2.8.2"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
pytest-xdist = "^2.2.1"
Sphinx = "^3.5.4"
sphinx-autoapi = "^1.8.1"
tox = "^3.23.0"
watchdog = "^2.0.3"
wheel = "^0.36.2"

[tool.poetry.extras]
backtrader = ["backtrader", "matplotlib"]
PyQt5 = ["PyQt5"]

[tool.poetry.scripts]
koapy = "koapy.cli:cli"

[tool.isort]
profile = "black"
src_paths = ["koapy"]
skip_glob = ["*_pb2.py", "*_pb2_grpc.py"]

[tool.black]
line-length = 88
extend-exclude = "(.+_pb2.py|.+_pb2_grpc.py)"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
